on:
  push:
    branches:
      - customdev

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: customdev
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: 🔨 Install Dependencies
        run: |
          npm install --legacy-peer-deps
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
          CI: false

      - name: 🏗 Build Project
        run: npm run build
        env:
          VITE_BASE_PATH: /ecommerce-frontend/

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./dist/
          server-dir: /${{ vars.SERVER_DIR }}/

